[project]
name = "language-modeling"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12, <3.13"
dependencies = []

[tool.uv.workspace]
members = ["lectures", "theory"]
